apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
//apply plugin: 'com.google.gms.google-services'
//apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdk 35

    defaultConfig {
        applicationId "com.mckimquyen.lenslauncher"
        minSdkVersion 25
        //noinspection EditedTargetSdkVersion
        targetSdkVersion 35
        versionCode 20250503
        versionName "2025.05.03"
    }

    android.applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = defaultConfig.applicationId + buildType.name + "_" + defaultConfig.versionName + "_" + defaultConfig.versionCode + ".apk"
        }
    }
    signingConfigs {
        release {
            storeFile file("keystore.jks")
            storePassword KS_PW
            keyAlias KS_ALIAS
            keyPassword KS_PW
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
//            applicationIdSuffix ".release"
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            applicationIdSuffix ".debug"
        }
    }

    flavorDimensions.add("type")
    productFlavors {

        dev {
//            applicationId = "com.mckimquyen.lenslauncher.dev"
            dimension "type"
            buildConfigField("String", "FLAVOR_buildEnv", '"dev"')
            resValue "string", "app_name", "Fisheye Launcher DEV"

            resValue("string", "SDK_KEY", "e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt")
            resValue "string", "BANNER", "aa291bda0fb0b6c5"
            resValue "string", "INTER", "7cf8ffccbdb242be"

            resValue("string", "EnableAdInter", "false")
            resValue("string", "EnableAdBanner", "true")
        }

        production {
//            applicationId = "com.mckimquyen.lenslauncher.prod"
            dimension "type"
            buildConfigField("String", "FLAVOR_buildEnv", '"prod"')
            resValue "string", "app_name", "Fisheye Launcher"
            resValue("string", "SDK_KEY", "e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt")
            resValue "string", "BANNER", "aa291bda0fb0b6c5"
            resValue "string", "INTER", "7cf8ffccbdb242be"

            resValue("string", "EnableAdInter", "true")
            resValue("string", "EnableAdBanner", "true")
        }

    }
//    dataBinding {
//        enabled = true
//    }

//    buildFeatures {
//        viewBinding true
//    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = 17
    }

    namespace 'com.mckimquyen'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
//    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.palette:palette-ktx:1.0.0'
    implementation 'com.github.satyan:sugar:1.5'
    implementation 'com.afollestad.material-dialogs:core:0.9.6.0'
    implementation 'com.afollestad.material-dialogs:commons:0.9.5.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation("androidx.webkit:webkit:1.12.1")

    //firebase
//    api platform('com.google.firebase:firebase-bom:33.2.0')
//    api 'com.google.firebase:firebase-analytics-ktx'
//    api 'com.google.firebase:firebase-crashlytics-ktx'
//    api 'com.google.firebase:firebase-config-ktx'

    //https://github.com/SimformSolutionsPvtLtd/SSBiometricsAuthentication
    implementation("androidx.biometric:biometric:1.2.0-alpha05")

    // debugImplementation because LeakCanary should only run in debug builds.
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'
//    implementation 'com.applovin:applovin-sdk:13.1.0'

    implementation("com.google.android.play:review:2.0.2")
    implementation("com.google.android.play:review-ktx:2.0.2")
}
